/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import com.tugatito.Aabsalon
import com.tugatito.Attribute
import com.tugatito.Phase
import kotlinx.serialization.Serializable
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class LibraryTest {
    @Test fun someLibraryMethodReturnsTrue() {
        val classUnderTest = Library()
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
    }

}
